blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/Zayan-Mohamed/orb/discussions
    about: Ask questions and discuss ideas with the community
  - name: ðŸ“– Documentation
    url: https://zayan-mohamed.github.io/orb/
    about: Read the full documentation
